### ISSUE TITLE
ClassNotFoundException with Maven Plugin.

### ISSUE THREAD

**Issue by LdSe** [fluxitsoft/jqa#16]
Hello guys,
I've been trying to test out the JQA Maven Plugin with one of our projects, and I've been unable to due to the following error: 

```
[INFO] An error occurred while executing the rules

Embedded error: java.lang.ClassNotFoundException: Exception while looking for class ar.com.xxx.test.backend.service.TestService: java.io.IOException: Couldn't find: ar/com/xxx/test/backend/service/TestService.class
```

I defined the following rulesContext:

```
<?xml version="1.0"?>
<jqa_ctx:RulesContext name="My rules conext"
xmlns:jqa="http://www.fluxit.com.ar/jqa/schema/ruleset"            
xmlns:jqa_ctx="http://www.fluxit.com.ar/jqa/schema/rulescontext"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.fluxit.com.ar/jqa/schema/rulescontext  
https://raw.github.com/jbaris/jqa/master/jqa-parent/jqa-ctx-factory-xmlbeans/src/main/resources/schema/rulescontext.xsd">

<ruleSet name="Services">
    <rule name="XXXService" message="El servicio debe implementar XXXService" priority="1">
        <filterPredicate xsi:type="jqa:AbstractionPredicate" abstractionType="CLASS"/>
        <checkPredicate xsi:type="jqa:TypingPredicate">
                <predicate xsi:type="jqa:NamingPredicate" namePattern="ar.com.xxx.services.XXXService" />
        </checkPredicate>
    </rule>
</ruleSet>

</jqa_ctx:RulesContext>
```

I'm also encountering this error with jqa-test-parent project:

```
Embedded error: java.lang.ClassNotFoundException: Exception while looking for class ar.com.fluxit.jqa.test.fmk.entity.Entity: java.io.IOException: Couldn't find
: ar/com/fluxit/jqa/test/fmk/entity/Entity.class
```

Not sure if it's still an active project, but it'd be great if you could shed some light onto this issue, since the project sounds great!

Thank you in advance.

**Comment by jbaris** [comment]
Hi
Can you post the output of "mvn -v" command?

Regards

**Comment by LdSe** [comment]
Sorry, forgot about that:

```
Apache Maven 2.2.1 (r801777; 2009-08-06 16:16:01-0300)
Java version: 1.6.0_25
Java home: C:\desarrollo\jdk\jdk1.6.0_25\jre
Default locale: es_ES, platform encoding: Cp1252
OS name: "windows 7" version: "6.1" arch: "amd64" Family: "windows"
```

Thanks for your prompt response.

**Comment by jbaris** [comment]
I think this is an OS problem. We have not yet test JQA under Windows environment.
Please, can you post detailed log of this error? I mean: "mvn ar.com.fluxit.jqa:jqa-maven-plugin:check -e"

Regards

**Comment by LdSe** [comment]
Here you go:

```
Embedded error: java.lang.ClassNotFoundException: Exception while looking for cl
ass ar.com.fluxit.jqa.test.fmk.entity.Entity: java.io.IOException: Couldn't find
: ar/com/fluxit/jqa/test/fmk/entity/Entity.class
[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: An error occurred while
executing the rules
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(Defa
ultLifecycleExecutor.java:719)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandalone
Goal(DefaultLifecycleExecutor.java:569)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(Defau
ltLifecycleExecutor.java:539)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHan
dleFailures(DefaultLifecycleExecutor.java:387)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegmen
ts(DefaultLifecycleExecutor.java:348)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLi
fecycleExecutor.java:180)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
        at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:6
0)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
        at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
        at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)

        at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: An error occurred whi
le executing the rules
        at ar.com.fluxit.jqa.JQAMavenPlugin.execute(JQAMavenPlugin.java:183)
        at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPlugi
nManager.java:490)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(Defa
ultLifecycleExecutor.java:694)
        ... 17 more
Caused by: java.lang.IllegalArgumentException: java.lang.ClassNotFoundException:
 Exception while looking for class ar.com.fluxit.jqa.test.fmk.entity.Entity: jav
a.io.IOException: Couldn't find: ar/com/fluxit/jqa/test/fmk/entity/Entity.class
        at ar.com.fluxit.jqa.bce.bcel.BCERepositoryImpl.getInterfaces(BCEReposit
oryImpl.java:382)
        at ar.com.fluxit.jqa.predicate.lang.TypingPredicate.evaluate(TypingPredi
cate.java:58)
        at ar.com.fluxit.jqa.predicate.ContextProvidedPredicate.evaluate(Context
ProvidedPredicate.java:70)
        at ar.com.fluxit.jqa.predicate.logic.OrPredicate.evaluate(OrPredicate.ja
va:50)
        at ar.com.fluxit.jqa.predicate.logic.NotPredicate.evaluate(NotPredicate.
java:62)
        at ar.com.fluxit.jqa.predicate.logic.AndPredicate.evaluate(AndPredicate.
java:50)
        at ar.com.fluxit.jqa.predicate.ContextProvidedPredicate.evaluate(Context
ProvidedPredicate.java:70)
        at ar.com.fluxit.jqa.RulesContextChecker.check(RulesContextChecker.java:
100)
        at ar.com.fluxit.jqa.RulesContextChecker.check(RulesContextChecker.java:
81)
        at ar.com.fluxit.jqa.RulesContextChecker.check(RulesContextChecker.java:
129)
        at ar.com.fluxit.jqa.JQAMavenPlugin.doExecute(JQAMavenPlugin.java:158)
        at ar.com.fluxit.jqa.JQAMavenPlugin.execute(JQAMavenPlugin.java:177)
        ... 19 more
Caused by: java.lang.ClassNotFoundException: Exception while looking for class a
r.com.fluxit.jqa.test.fmk.entity.Entity: java.io.IOException: Couldn't find: ar/
com/fluxit/jqa/test/fmk/entity/Entity.class
        at org.apache.bcel.util.SyntheticRepository.loadClass(SyntheticRepositor
y.java:128)
        at org.apache.bcel.classfile.JavaClass.getInterfaces(JavaClass.java:788)

        at org.apache.bcel.classfile.JavaClass.getAllInterfaces(JavaClass.java:8
04)
        at org.apache.bcel.Repository.getInterfaces(Repository.java:161)
        at ar.com.fluxit.jqa.bce.bcel.BCERepositoryImpl.getInterfaces(BCEReposit
oryImpl.java:374)
        ... 30 more
```

Thank you.

**Comment by jbaris** [comment]
I made some changes for cross-platform compability. Please, try the new code and tell us if it works for you.

Regards

**Comment by LdSe** [comment]
Just made the test with the sample project, it worked!

Thanks a lot!
